'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.17020
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("MetroUI_Form.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _100() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_100", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _108() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("108", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _91() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("91", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _next() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("next", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property abt_background() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("abt_background", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;html&gt;
        '''
        '''    &lt;head&gt;
        '''    	&lt;meta http-equiv=&quot;content-type&quot; content=&quot;text/html; charset=UTF-8&quot;&gt;
        '''        &lt;title&gt;Installed Plug-ins&lt;/title&gt;
        '''	&lt;style type=&quot;text/css&quot;&gt;
        '''            body { color: #555; }
        '''            div#margins { margin: 5%; }
        '''            
        '''            div.plugin-name {
        '''                margin-top: 2em;
        '''                margin-bottom: 1en;
        '''                font-size: large;
        '''                font-weight: bold;
        '''                color: black;
        '''            }
        '''            
        '''            table {
        '''    [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property abtplgins() As String
            Get
                Return ResourceManager.GetString("abtplgins", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property add() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("add", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property back() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("back", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property back1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("back1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property button_clicked() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_clicked", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property button_hover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_hover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property button_normal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_normal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cancel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cancel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cancel1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cancel1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property check() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("check", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property check1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("check1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property check2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("check2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property check3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("check3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        '''&lt;html&gt;
        '''
        '''&lt;head&gt;
        '''&lt;meta content=&quot;en-us&quot; http-equiv=&quot;Content-Language&quot;&gt;
        '''&lt;meta content=&quot;text/html; charset=utf-8&quot; http-equiv=&quot;Content-Type&quot;&gt;
        '''&lt;title&gt;Error&lt;/title&gt;
        '''&lt;style type=&quot;text/css&quot;&gt;
        '''.auto-style1 {
        '''	font-family: &quot;Segoe UI&quot;, Tahoma, Geneva, Verdana, sans-serif;
        '''	font-size: 50pt;
        '''	text-align: center;
        '''}
        '''.auto-style3 {
        '''	font-family: &quot;Segoe UI&quot;, Tahoma, Geneva, Verdana, sans-serif;
        '''	font-size: 25pt;
        '''	text-align: center;
        '''}
        '''.auto-style4 {
        '''	font-size: medium;
        '''}
        '''.auto-style5 {
        '''	fo [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Err() As String
            Get
                Return ResourceManager.GetString("Err", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property facebook_button() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("facebook_button", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property favs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("favs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property favs_addto() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("favs.addto", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property folder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("folder", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property go() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("go", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property google() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("google", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property hp_safari_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hp-safari-icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Metro_Apps4_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Metro-Apps4-32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Metro_Forward_Black_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Metro-Forward-Black-32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property multicolor_metro_ui_windows_8_7___Copy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("multicolor_metro_ui_windows_8_7___Copy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        '''&lt;html&gt;
        '''
        '''&lt;head&gt;
        '''&lt;meta content=&quot;en-us&quot; http-equiv=&quot;Content-Language&quot;&gt;
        '''&lt;meta content=&quot;text/html; charset=utf-8&quot; http-equiv=&quot;Content-Type&quot;&gt;
        '''&lt;title&gt;Warning: Phish&lt;/title&gt;
        '''&lt;style type=&quot;text/css&quot;&gt;
        '''.auto-style1 {
        '''	font-family: &quot;Segoe UI&quot;, Tahoma, Geneva, Verdana, sans-serif;
        '''}
        '''.auto-style2 {
        '''	font-size: x-large;
        '''	color: #FF0000;
        '''}
        '''.auto-style3 {
        '''	font-size: large;
        '''}
        '''.auto-style4 {
        '''	vertical-align: baseline;
        '''}
        '''.auto-style5 {
        '''	text-align: center;
        '''}
        '''.auto-style6 {
        '''	font-family: [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property phishdetected() As String
            Get
                Return ResourceManager.GetString("phishdetected", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property refresh() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("refresh", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sadface() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sadface", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property save() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("save", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property search() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("search", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property settings() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("settings", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property tab_back() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tab_back", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
