'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.235
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("MetroUI_Form.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _100() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_100", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _108() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("108", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _next() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("next", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;html&gt;
        '''
        '''    &lt;head&gt;
        '''    	&lt;meta http-equiv=&quot;content-type&quot; content=&quot;text/html; charset=UTF-8&quot;&gt;
        '''        &lt;title&gt;Installed Plug-ins&lt;/title&gt;
        '''	&lt;style type=&quot;text/css&quot;&gt;
        '''            body { color: #555; }
        '''            div#margins { margin: 5%; }
        '''            
        '''            div.plugin-name {
        '''                margin-top: 2em;
        '''                margin-bottom: 1en;
        '''                font-size: large;
        '''                font-weight: bold;
        '''                color: black;
        '''            }
        '''            
        '''            table {
        '''    [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property abtplgins() As String
            Get
                Return ResourceManager.GetString("abtplgins", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property back() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("back", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property back1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("back1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cancel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cancel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cancel1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cancel1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property check() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("check", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property check1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("check1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property check2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("check2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property check3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("check3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;html i18n-values=&quot;dir:textdirection&quot; dir=&quot;ltr&quot;&gt;&lt;head&gt;
        '''&lt;title i18n-content=&quot;title&quot;&gt;Canure cannot open this webpage&lt;/title&gt;
        '''&lt;style&gt;
        '''body {
        '''  background-color: #fff;
        '''  color: #000;
        '''  font-family: Helvetica, Arial, sans-serif;
        '''  font-size: 83%;
        '''  line-height: 120%;
        '''  max-width: 35em;
        '''  padding: 0.5em 1em;
        '''}
        '''li {
        '''  padding-bottom: .3em;
        '''}
        '''ul {
        '''  margin: .5em 0 0;
        '''  padding-bottom: 0;
        '''}
        '''h1 {
        '''  font-size: 1.5em;
        '''  margin-bottom: 1.5em;
        '''}
        '''h2 {
        '''  font-size: 1em;
        '''  font-weight: bold;
        '''  marg [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Err() As String
            Get
                Return ResourceManager.GetString("Err", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property favs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("favs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property favs_addto() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("favs.addto", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property folder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("folder", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property go() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("go", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Metro_Apps4_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Metro-Apps4-32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Metro_Forward_Black_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Metro-Forward-Black-32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property refresh() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("refresh", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property save() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("save", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property search() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("search", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property settings() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("settings", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        '''&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        '''
        '''&lt;head&gt;
        '''&lt;meta content=&quot;en-us&quot; http-equiv=&quot;Content-Language&quot; /&gt;
        '''&lt;meta content=&quot;text/html; charset=utf-8&quot; http-equiv=&quot;Content-Type&quot; /&gt;
        '''&lt;title&gt;Canure 2.3&lt;/title&gt;
        '''&lt;style type=&quot;text/css&quot;&gt;
        '''.auto-style1 {
        '''	font-family: Calibri;
        '''}
        '''.auto-style2 {
        '''	font-family: Calibri;
        '''	color: #342D2D;
        '''}
        '''.auto-style3 {
        '''	color: #342D2D;
        '''}
        '''.auto-style4 { [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property welcome() As String
            Get
                Return ResourceManager.GetString("welcome", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
